routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
Route::get('/', 'ProdukController@index');


Route::resource('produk', 'ProdukController');
Route::resource('customer', 'CustomerController');
Route::resource('transaksi', 'TransaksiController');
Route::resource('histori', 'HistoriController');

app/Histori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Histori extends Model
{
    protected $table = "histori";

    protected $guarded = array();
}

app/Http/Controllers/API/HistoriController.php
<?php

namespace App\Http\Controllers\API;

use App\Histori;
use Illuminate\Http\Request;

class HistoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data  = Histori::all();
        return response()->json($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    { }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $create = Histori::create($request->all());
        if ($create) {
            return response()->json(
                [
                    "error" =>  false
                ]
            );
        } else {
            return response()->json(
                [
                    "error" =>  true
                ]
            );
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Histori  $histori
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $histori = Histori::where("id", $id)
            ->orWhere("uid", $id)
            ->latest('created_at')
            ->first();

        return response()->json($histori);

    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Histori  $histori
     * @return \Illuminate\Http\Response
     */
    public function edit(Histori $histori)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Histori  $histori
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Histori  $histori
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = Histori::findOrFail($id)->delete();
        return response()->json($delete);
    }
}

app/Http/Controllers/HistoriController.php
<?php

namespace App\Http\Controllers;

use App\Histori;
use Illuminate\Http\Request;

class HistoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data  = Histori::all();
        return view('histori.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('histori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $create = Histori::create($request->all());
        return redirect('/histori');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Histori  $histori
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $histori = Histori::where("id", $id)
            ->orWhere("uid", $id)
            ->latest('created_at')
            ->first();

        return response()->json($histori);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Histori  $histori
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Histori::findOrFail($id);
        return view('histori.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Histori  $histori
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $histori = Histori::findOrFail($id);
        $histori->update($request->all());
        return redirect('/histori');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Histori  $histori
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Histori::findOrFail($id)->delete();
        return redirect('/histori');
    }
}

resources/views/histori/create.blade.php
@extends('layouts.app')
@section('content')
<form method="POST" action="{{ route('histori.store') }}" enctype="multipart/form-data">
  {{ csrf_field() }}
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header"><strong>Pengisian</strong><small>Buat Histori</small></div>
      <div class="card-body card-block">
        <div class="form-group">
            <label for="kode" class=" form-control-label">UID</label><input type="text" id="kode" placeholder="" name="kode" class="form-control" required=""></div>
        <div class="form-group">
            <label for="nama" class=" form-control-label">Saloo Awal</label><input type="text" id="nama" placeholder="" name="nama" class="form-control" required=""></div>
        <div class="form-group">
            <label for="harga" class=" form-control-label">Saldo Akhir</label><input type="number" id="harga" name="harga" placeholder="" class="form-control" required=""></div>
            <div class="form-group">
                <label for="harga" class=" form-control-label">Total Harga</label><input type="number" id="total_harga" name="harga" placeholder="" class="form-control" required="" value=""></div>
        <div class="form-group">
            <label for="stock" class=" form-control-label">Status</label><input type="number" id="stock" placeholder="" name="stock" class="form-control" required=""></div>
      </div>
      <button type="submit" class="btn btn-primary" id="submit">
      Submit
    </div>
  </div>
</form>
@endsection

resources/views/histori/edit.blade.php
@extends('layouts.app')
@section('content')
<form method="POST" action="{{ route('histori.update', $data->id) }}" enctype="multipart/form-data">
  {{ csrf_field() }}
  {{ method_field('put') }}
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header"><strong>Pengisian</strong><small>Edit Produk</small></div>
      <div class="card-body card-block">
        <div class="form-group">
            <label for="kode" class=" form-control-label">UID</label><input type="text" id="uid" name="kode" class="form-control" required="" value="{{$data->uid}}"></div>
        <div class="form-group">
            <label for="nama" class=" form-control-label">Saldo Awal</label><input type="text" id="saldo_awal" placeholder="" name="nama" class="form-control" required="" value="{{$data->saldo_awal}}"></div>
        <div class="form-group">
            <label for="harga" class=" form-control-label">Saldo Akhir</label><input type="number" id="saldo_akhir" name="harga" placeholder="" class="form-control" required="" value="{{$data->saldo_akhir}}"></div>
            <div class="form-group">
                <label for="harga" class=" form-control-label">Total Harga</label><input type="number" id="total_harga" name="harga" placeholder="" class="form-control" required="" value="{{$data->total_harga}}"></div>
        <div class="form-group">
            <label for="stock" class=" form-control-label">Status</label><input type="number" id="status" name="stock" placeholder="" class="form-control" required="" value="{{$data->status}}"></div>

      </div>
      <button type="submit" class="btn btn-primary" id="submit">
      Submit
    </div>
  </div>
</form>

@endsection

resources/views/histori/index.blade.php
@extends('layouts.app')
@section('content')
<button type="button" name="button" class="btn btn-primary" href="#"><a href="#">Tambah Data</a></button>
<br>
<br>
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <strong class="card-title">Data Table</strong>
    </div>
    <div class="card-body">
      <table id="bootstrap-data-table-export" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>UID</th>
            <th>Saldo awal</th>
            <th>Saldo akhir</th>
            <th>total harga</th>
            <th>status</th>
            <th>tanggal</th>
          </tr>
        </thead>
        <tbody>
          @foreach($datas as $data)
          <tr>
            <td>{{$data->uid}}</td>
            <td>{{$data->saldo_awal}}</td>
            <td>{{$data->saldo_akhir}}</td>
            <td>{{$data->total_harga}}</td>
            <td>{{$data->status}}</td>
            <td>{{$data->created_at}}</td>
            <td>
              <div class="btn-group dropdown">
                <button type="button" class="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Action
                </button>
                <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 30px, 0px);">
                  <a class="dropdown-item" href="#"> Edit </a>
                  <form action="{{ route('histori.destroy', $data->id) }}" class="pull-left"  method="post">
                    {{ csrf_field() }}
                    {{ method_field('delete') }}
                    <button class="dropdown-item" onclick="return confirm('Anda yakin ingin menghapus data ini?')"> Delete
                    </button>
                  </form>
                </div>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection