routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
Route::get('/', 'ProdukController@index');


Route::resource('produk', 'ProdukController');
Route::resource('customer', 'CustomerController');
Route::resource('transaksi', 'TransaksiController');
Route::resource('histori', 'HistoriController');

app/Transaksi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    protected $table = "transaksi";
    protected $guarded = [];
}

app/Http/Controllers/API/TransaksiController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Support\Facades\DB;
use App\Transaksi;
use Illuminate\Http\Request;

class TransaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $datas = DB::table("transaksi")
            ->select(
                "transaksi.id as id",
                "customer.nama as customer",
                "transaksi.produk_id as produk",
                "transaksi.jumlah_per_produk",
                "transaksi.subtotal_per_produk",
                "transaksi.total_harga",
                "transaksi.created_at as tanggal"
            )
            ->leftjoin("customer", "transaksi.customer_id", "customer.id")
            ->orderByDesc("transaksi.created_at")
            ->get();

        return response()->json($datas);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $cust = Transaksi::create($request->all());
        if ($cust) {
            return response()->json(
                [
                    "error" =>  false
                ]
            );
        } else {
            return response()->json(
                [
                    "error" =>  true
                ]
            );
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function showByCustomer($id)
    {

        $data = DB::table("transaksi")
            ->select(
                "customer.nama as customer",
                "transaksi.produk_id as produk",
                "transaksi.jumlah_per_produk",
                "transaksi.subtotal_per_produk",
                "transaksi.total_harga",
                "transaksi.created_at as tanggal"
            )
            ->leftjoin("customer", "transaksi.customer_id", "customer.id")
            ->where("transaksi.customer_id", $id)
            ->orderByDesc("transaksi.created_at")
            ->get();

        return response()->json($data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaksi $transaksi)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaksi $transaksi)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaksi $transaksi)
    {
        //
    }
}

app/Http/Controllers/TransaksiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\DB;
use App\Transaksi;
use Illuminate\Http\Request;

class TransaksiController extends Controller
{

    public function index()
    {

        $datas = DB::table("transaksi")
        ->select(
            "transaksi.id as id",
            "customer.nama as customer",
            "transaksi.produk_id as produk",
            "transaksi.jumlah_per_produk",
            "transaksi.subtotal_per_produk",
            "transaksi.total_harga"
        )
        ->leftjoin("customer", "transaksi.customer_id", "customer.id")
        ->orderByDesc("transaksi.created_at")
        ->get();

        return view('transaksi.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('transaksi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Transaksi::create($request->all());
        return redirect('/transaksi');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function showByCustomer($id)
    {

        $datas = DB::table("transaksi")
        ->select(
            "transaksi.id as id",
            "customer.nama as customer",
            "transaksi.produk_id as produk",
            "transaksi.jumlah_per_produk",
            "transaksi.subtotal_per_produk",
            "transaksi.total_harga"
        )
        ->leftjoin("customer", "transaksi.customer_id", "customer.id")
          ->where('transaksi.customer_id', $id)
        ->orderByDesc("transaksi.created_at")
        ->get();
            
        return view('transaksi.index', compact('datas'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Transaksi::findOrFail($id);
        return view('transaksi.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaksi  $transaksi
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Transaksi::find($id)->update([
            'customer_id' => $request->get('customer_id'),
            'produk_id' => $request->get('produk_id'),
            'subtotal_per_produk' => $request->get('subtotal_per_produk'),
            'jumlah_per_produk' => $request->get('jumlah_per_produk'),
            'total_harga' => $request->get('total_harga')
        ]);

        $datas = Transaksi::get();
        return redirect('/transaksi');
    }


    public function destroy($id)
    {
        Transaksi::find($id)->delete();
        return redirect('/transaksi');
    }
}

resources/views/transaksi/create.blade.php
@extends('layouts.app')
@section('content')
<form method="POST" action="{{ route('produk.store') }}" enctype="multipart/form-data">
  {{ csrf_field() }}
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header"><strong>Pengisian</strong><small>Buat Produk</small></div>
      <div class="card-body card-block">
        <div class="form-group">
            <label for="kode" class=" form-control-label">Kode</label><input type="text" id="kode" placeholder="" name="kode" class="form-control" required=""></div>
        <div class="form-group">
            <label for="nama" class=" form-control-label">Nama</label><input type="text" id="nama" placeholder="0209487" name="nama" class="form-control" required=""></div>
        <div class="form-group">
            <label for="harga" class=" form-control-label">Harga</label><input type="number" id="harga" name="harga" placeholder="Rp 900.000.000" class="form-control" required=""></div>
        <div class="form-group">
            <label for="stock" class=" form-control-label">Stock</label><input type="number" id="stock" placeholder="" name="stock" class="form-control" required=""></div>
      </div>
      <button type="submit" class="btn btn-primary" id="submit">
      Submit
    </div>
  </div>
</form>
@endsection

resources/views/transaksi/edit.blade.php
@extends('layouts.app')
@section('content')
<form method="POST" action="{{ route('transaksi.update', $data->id) }}" enctype="multipart/form-data">
  {{ csrf_field() }}
  {{ method_field('put') }}
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header"><strong>Pengisian</strong><small>Edit Produk</small></div>
      <div class="card-body card-block">
        <div class="form-group">
            <label for="kode" class=" form-control-label">Id Customer</label><input type="text" id="kode" name="kode" class="form-control" required="" value="{{$data->customer_id}}"></div>
        <div class="form-group">
            <label for="nama" class=" form-control-label">Produk set berdasrkan id (Pisahkan dengan koma)</label><input type="text" id="nama" placeholder="0209487" name="nama" class="form-control" required="" value="{{$data->nama}}"></div>
        <div class="form-group">
            <label for="harga" class=" form-control-label">Jumlah per produk (Pisahkan dengan koma)</label><input type="number" id="harga" name="harga" placeholder="Rp 900.000.000" class="form-control" required="" value="{{$data->harga}}"></div>
        <div class="form-group">
            <label for="stock" class=" form-control-label">Stock</label><input type="number" id="stock" name="stock" placeholder="" class="form-control" required="" value="{{$data->stock}}"></div>
        <div class="form-group"><label for="harga" class=" form-control-label">Harga</label><input type="number" id="harga" placeholder="" name="harga" class="form-control" required="" value="{{$data->harga}}"></div>

      </div>
      <button type="submit" class="btn btn-primary" id="submit">
      Submit
    </div>
  </div>
</form>

@endsection

resources/views/transaksi/index.blade.php
@extends('layouts.app')
@section('content')
<button type="button" name="button" class="btn btn-primary" href="#"><a href="#">Tambah Data</a></button>
<br>
<br>
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <strong class="card-title">Data Table</strong>
    </div>
    <div class="card-body">
      <table id="bootstrap-data-table-export" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>customer</th>
            <th>Set Produk</th>
            <th>Set Jumlah Per Produk</th>
            <th>Set Subtotal Per Produk</th>
            <th>Total Harga</th>
          </tr>
        </thead>
        <tbody>
          @foreach($datas as $data)
          <tr>
            <td>{{$data->customer}}</td>
            <td>{{$data->produk}}</td>
            <td>{{$data->jumlah_per_produk}}</td>
            <td>{{$data->subtotal_per_produk}}</td>
            <td>{{$data->total_harga}}</td>
            <td>
              <div class="btn-group dropdown">
                <button type="button" class="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Action
                </button>
                <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 30px, 0px);">
                  <a class="dropdown-item" href="#"> Edit </a>
                  <form action="{{ route('transaksi.destroy', $data->id) }}" class="pull-left"  method="post">
                    {{ csrf_field() }}
                    {{ method_field('delete') }}
                    <button class="dropdown-item" onclick="return confirm('Anda yakin ingin menghapus data ini?')"> Delete
                    </button>
                  </form>
                </div>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection