routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
Route::get('/', 'ProdukController@index');


Route::resource('produk', 'ProdukController');
Route::resource('customer', 'CustomerController');
Route::resource('transaksi', 'TransaksiController');
Route::resource('histori', 'HistoriController');

app/Produk.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    protected $table = "produk";

    protected $fillable = [
        'nama',
        'harga',
        'stock',
        'kode'
    ];
}

app/Http/Controllers/API/ProdukController.php
<?php

namespace App\Http\Controllers\API;

use App\Produk;
use Illuminate\Http\Request;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Produk::all();
        return response()->json($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('produk.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $produk = Produk::create($request->all());
        return response()->json($produk);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
        $produk = Produk::where('kode', $id)->first();
        return response()->json($produk);
    }

    public function showByCode($code){

        $produk = Produk::where('kode', $code)->first();
        return response()->json($produk);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Produk::findOrFail($id);
        return view('produk.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $update = Produk::find($id)->update([
            'kode' => $request->get('kode'),
            'nama' => $request->get('nama'),
            'harga' => $request->get('harga'),
            'stock' => $request->get('stock')
        ]);

        return response()->json($update);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = Produk::find($id)->delete();
        return response()->json($delete);
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use App\Produk;
use Illuminate\Http\Request;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = Produk::all();
        return view('produk.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('produk.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Produk::create($request->all());
        return redirect('/produk');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function show(Produk $produk)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Produk::findOrFail($id);
        return view('produk.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Produk::find($id)->update([
            'kode' => $request->get('kode'),
            'nama' => $request->get('nama'),
            'harga' => $request->get('harga'),
            'stock' => $request->get('stock')
          ]);

          $datas = Produk::get();
          return redirect('/produk');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Produk  $produk
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Produk::find($id)->delete();
        return redirect('/produk');
    }
}

resources/views/produk/create.blade.php
@extends('layouts.app')
@section('content')
<form method="POST" action="{{ route('produk.store') }}" enctype="multipart/form-data">
  {{ csrf_field() }}
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header"><strong>Pengisian</strong><small>Buat Produk</small></div>
      <div class="card-body card-block">
        <div class="form-group">
            <label for="kode" class=" form-control-label">Kode</label><input type="text" id="kode" placeholder="" name="kode" class="form-control" required=""></div>
        <div class="form-group">
            <label for="nama" class=" form-control-label">Nama</label><input type="text" id="nama" placeholder="" name="nama" class="form-control" required=""></div>
        <div class="form-group">
            <label for="harga" class=" form-control-label">Harga</label><input type="number" id="harga" name="harga" placeholder="90000" class="form-control" required=""></div>
        <div class="form-group">
            <label for="stock" class=" form-control-label">Stock</label><input type="number" id="stock" placeholder="" name="stock" class="form-control" required=""></div>
      </div>
      <button type="submit" class="btn btn-primary" id="submit">
      Submit
    </div>
  </div>
</form>
@endsection

resources/views/produk/edit.blade.php
@extends('layouts.app')
@section('content')
<form method="POST" action="{{ route('produk.update', $data->id) }}" enctype="multipart/form-data">
  {{ csrf_field() }}
  {{ method_field('put') }}
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header"><strong>Pengisian</strong><small>Edit Produk</small></div>
      <div class="card-body card-block">
        <div class="form-group">
            <label for="kode" class=" form-control-label">Kode</label><input type="text" id="kode" name="kode" class="form-control" required="" value="{{$data->kode}}"></div>
        <div class="form-group">
            <label for="nama" class=" form-control-label">Nama</label><input type="text" id="nama" placeholder="" name="nama" class="form-control" required="" value="{{$data->nama}}"></div>
        <div class="form-group">
            <label for="harga" class=" form-control-label">Harga</label><input type="number" id="harga" name="harga" placeholder="90000" class="form-control" required="" value="{{$data->harga}}"></div>
        <div class="form-group">
            <label for="stock" class=" form-control-label">Stock</label><input type="number" id="stock" name="stock" placeholder="" class="form-control" required="" value="{{$data->stock}}"></div>
        <!-- <div class="form-group"><label for="kantor_cabang" class=" form-control-label">Kantor Cabang</label>
          <select class="form-control" name="kantor_cabang" required="">
            <option value=""></option>
            <option value="BND">KCP Bandung</option>
            <option value="DPK">KCP Depok</option>
            <option value="TGS">KCP Tangsel</option>
          </select>
        </div> -->
        <div class="form-group"><label for="harga" class=" form-control-label">Harga</label><input type="number" id="harga" placeholder="" name="harga" class="form-control" required="" value="{{$data->harga}}"></div>

      </div>
      <button type="submit" class="btn btn-primary" id="submit">
      Submit
    </div>
  </div>
</form>

@endsection

resources/views/produk/index.blade.php
@extends('layouts.app')
@section('content')
<button type="button" name="button" class="btn btn-primary" href="{{route('produk.create')}}"><a href="{{route('produk.create')}}">Tambah Data</a></button>
<br>
<br>
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <strong class="card-title">Data Table</strong>
    </div>
    <div class="card-body">
      <table id="bootstrap-data-table-export" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Id</th>
            <th>Kode</th>
            <th>Nama</th>
            <th>Harga</th>
            <th>Stock</th>
          </tr>
        </thead>
        <tbody>
          @foreach($datas as $data)
          <tr>
            <td>{{$data->id}}</td>
            <td>{{$data->kode}}</td>
            <td>{{$data->nama}}</td>
            <td>{{$data->harga}}</td>
            <td>{{$data->stock}}</td>
            <td>
              <div class="btn-group dropdown">
                <button type="button" class="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Action
                </button>
                <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 30px, 0px);">
                  <a class="dropdown-item" href="{{route('produk.edit', $data->id)}}"> Edit </a>
                  <form action="{{ route('produk.destroy', $data->id) }}" class="pull-left"  method="post">
                    {{ csrf_field() }}
                    {{ method_field('delete') }}
                    <button class="dropdown-item" onclick="return confirm('Anda yakin ingin menghapus data ini?')"> Delete
                    </button>
                  </form>
                </div>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection