routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
Route::get('/', 'ProdukController@index');


Route::resource('produk', 'ProdukController');
Route::resource('customer', 'CustomerController');
Route::resource('transaksi', 'TransaksiController');
Route::resource('histori', 'HistoriController');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $table = "customer";

    protected $fillable = [
        'nama',
        'email',
        'password',
        'saldo'
    ];

}

app/Http/Controllers/API/CustomerController.php
<?php

namespace App\Http\Controllers\API;

use App\Customer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Customer::all();
        return response()->json($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Responseø
     */
    public function store(Request $request)
    {

        //regis

        $customer = $request->all();
        $cust = Customer::create([
            'email' => $customer['email'],
            'password' => Hash::make($customer['password']),
            'nama' => $customer['nama'],
            'saldo' => $customer['saldo']
        ]);
        
        if($cust){
             return response()->json([
         "error" =>  false
            ]
            );
        }
        
        else{
                 return response()->json([
         "error" =>  true
            ]
            );
        }

       
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
     
    public function show($id){
         
         $data = Customer::findOrFail($id);
         return response()->json($data);
         
     }
    public function login(Request $request)
    {

        $email = $request->email;
        $password = $request->password;

        $log_email = Customer::where('email', $email)->count();

        if ($log_email == null || $log_email == 0) {
            $message = "Email anda tidak terdaftar !";
            $berhasil = false;
            $id = null;
        } else {
            $log_pass = Customer::select('id', 'password')->where('email', $email)->first();
            $check = Hash::check($password, $log_pass->password);

            if ($check) {
                $message = "Silahkan masuk";
                $berhasil = true;
                $id = $log_pass->id;
            } else {
                $message = "Password salah !";
                $berhasil = false;
                $id = null;
            }
        }
        return response()->json([
            "message" => $message,
            "error" => !$berhasil,
            "id" => $id
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Customer::findOrFail($id);
        return view('customer.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $customer = Customer::find($id)->update([
            'nama' => $request->get('nama'),
            'email' => $request->get('email'),
            'password' => Hash::make($request->get('password')),
            'saldo' => $request->get('saldo')
        ]);


      if($customer){
             return response()->json([
         "error" =>  false
            ]
            );
        }
        
        else{
                 return response()->json([
         "error" =>  true
            ]
            );
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $del = Customer::find($id)->delete();
         if($del){
             return response()->json([
         "error" =>  false
            ]
            );
        }
        
        else{
                 return response()->json([
         "error" =>  true
            ]
            );
        }
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $datas = Customer::all();
        return view('customer.index', compact('datas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('customer.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Responseø
     */
    public function store(Request $request)
    {

        $customer = $request->all();
        Customer::create([
            'email' => $customer['email'],
            'password' => Hash::make($customer['password']),
            'nama' => $customer['nama'],
            'saldo' => $customer['saldo']
        ]);

        return redirect('/customer');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request)
    {
        //login
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Customer::findOrFail($id);
        return view('customer.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Customer::find($id)->update([
            'nama' => $request->get('nama'),
            'email' => $request->get('email'),
            'password' => Hash::make($request->get('password')),
            'saldo' => $request->get('saldo')
        ]);

        $datas = Customer::get();
        return redirect('/customer');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Customer::find($id)->delete();
        return redirect('/customer');
    }
}

resources/views/customer/create.blade.php
@extends('layouts.app')
@section('content')
<form method="POST" action="{{ route('customer.store') }}" enctype="multipart/form-data">
  {{ csrf_field() }}
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header"><strong>Pengisian</strong><small>Buat Produk</small></div>
      <div class="card-body card-block">
            <div class="form-group">
                    <label for="kode" class=" form-control-label">Nama</label><input type="text" id="nama" name="nama" class="form-control" required=""></div>
                <div class="form-group">
                    <label for="nama" class=" form-control-label">Email</label><input type="text" id="email" placeholder="" name="email" class="form-control" required="" ></div>
                <div class="form-group">
                    <label for="harga" class=" form-control-label">Password</label><input type="text" id="password" name="password" placeholder="password" class="form-control" required=""></div>
                <div class="form-group">
                    <label for="stock" class=" form-control-label">Saldo</label><input type="number" id="saldo" name="saldo" placeholder="900000" class="form-control" "></div>
                     <div class="form-group">
                    <label for="uid" class=" form-control-label">UID</label><input type="text" id="uid" name="uid" placeholder="" class="form-control" "></div>

      </div>
      <button type="submit" class="btn btn-primary" id="submit">
      Submit
    </div>
  </div>
</form>
@endsection

resources/views/customer/edit.blade.php
@extends('layouts.app')
@section('content')
<form method="POST" action="{{ route('customer.update', $data->id) }}" enctype="multipart/form-data">
  {{ csrf_field() }}
  {{ method_field('put') }}
  <div class="col-lg-6">
    <div class="card">
      <div class="card-header"><strong>Pengisian</strong><small>Edit Customer</small></div>
      <div class="card-body card-block">
        <div class="form-group">
            <label for="kode" class=" form-control-label">Nama</label><input type="text" id="nama" name="nama" class="form-control" required="" value="{{$data->nama}}"></div>
        <div class="form-group">
            <label for="nama" class=" form-control-label">Email</label><input type="text" id="email" placeholder="" name="email" class="form-control" required="" value="{{$data->email}}"></div>
        <div class="form-group">
            <label for="harga" class=" form-control-label">Password</label><input type="text" id="password" name="password" placeholder="" class="form-control" required="" "></div>
        <div class="form-group">
            <label for="stock" class=" form-control-label">Saldo</label><input type="number" id="saldo" name="saldo" placeholder="" class="form-control" required="" value="{{$data->saldo}}"></div>
        <div class="form-group">
            <label for="uid" class=" form-control-label">UID</label><input type="text" id="uid" name="uid" placeholder="" class="form-control" required="" value="{{$data->uid}}"></div>

      </div>
      <button type="submit" class="btn btn-primary" id="submit">
      Submit
    </div>
  </div>
</form>

@endsection

resources/views/customer/index.blade.php
@extends('layouts.app')
@section('content')
<button type="button" name="button" class="btn btn-primary" href="{{route('customer.create')}}"><a href="{{route('customer.create')}}">Tambah Data</a></button>
<br>
<br>
<div class="col-md-12">
  <div class="card">
    <div class="card-header">
      <strong class="card-title">Data Table</strong>
    </div>
    <div class="card-body">
      <table id="bootstrap-data-table-export" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Id</th>
            <th>Email</th>
             <th>UID</th>
            <th>Nama</th>
            <th>Saldo</th>
            <th>Tanggal Daftar</th>
          </tr>
        </thead>
        <tbody>
          @foreach($datas as $data)
          <tr>
            <td>{{$data->id}}</td>
            <td>{{$data->email}}</td>
            <td>{{$data->uid}}</td>
            <td>{{$data->nama}}</td>
            <td>{{$data->saldo}}</td>
            <td>{{$data->created_at}}</td>
            <td>
              <div class="btn-group dropdown">
                <button type="button" class="btn btn-success dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Action
                </button>
                <div class="dropdown-menu" x-placement="bottom-start" style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(0px, 30px, 0px);">
                  <a class="dropdown-item" href="{{route('customer.edit', $data->id)}}"> Edit </a>
                  <form action="{{ route('customer.destroy', $data->id) }}" class="pull-left"  method="post">
                    {{ csrf_field() }}
                    {{ method_field('delete') }}
                    <button class="dropdown-item" onclick="return confirm('Anda yakin ingin menghapus data ini?')"> Delete
                    </button>
                  </form>
                </div>
              </div>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>
    </div>
  </div>
</div>
@endsection